// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCyVTBdAKPnErzmVRbw_AKTC0UEurzmDY0',
    appId: '1:941222051288:web:98b3bc2dd843c849ab46ad',
    messagingSenderId: '941222051288',
    projectId: 'expense-app-a5b1e',
    authDomain: 'expense-app-a5b1e.firebaseapp.com',
    storageBucket: 'expense-app-a5b1e.appspot.com',
    measurementId: 'G-N4W2ESHMJ0',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAf1nQ2fBiMrjUSHlhmm_mw0bJIJn8whw0',
    appId: '1:941222051288:android:042fca0059b30478ab46ad',
    messagingSenderId: '941222051288',
    projectId: 'expense-app-a5b1e',
    storageBucket: 'expense-app-a5b1e.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAyCmLeCvsgmv4_VxZUQSZTSBL0rVnEkOo',
    appId: '1:941222051288:ios:7c5c729610f507f4ab46ad',
    messagingSenderId: '941222051288',
    projectId: 'expense-app-a5b1e',
    storageBucket: 'expense-app-a5b1e.appspot.com',
    iosClientId: '941222051288-ub8dgsf4j68n7q8r0d3l5qrbi4ao7cjm.apps.googleusercontent.com',
    iosBundleId: 'com.example.expenseApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAyCmLeCvsgmv4_VxZUQSZTSBL0rVnEkOo',
    appId: '1:941222051288:ios:7c5c729610f507f4ab46ad',
    messagingSenderId: '941222051288',
    projectId: 'expense-app-a5b1e',
    storageBucket: 'expense-app-a5b1e.appspot.com',
    iosClientId: '941222051288-ub8dgsf4j68n7q8r0d3l5qrbi4ao7cjm.apps.googleusercontent.com',
    iosBundleId: 'com.example.expenseApp',
  );
}
